2018-12-27 08:17:31,012 reveal_service.py[line:149] ERROR [async_call] 异常，重试1次 id=280 roomid=10 game_id=254 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 08:17:33,115 reveal_service.py[line:149] ERROR [async_call] 异常，重试2次 id=280 roomid=10 game_id=254 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 08:17:36,033 reveal_service.py[line:149] ERROR [async_call] 异常，重试3次 id=280 roomid=10 game_id=254 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 08:17:39,955 reveal_service.py[line:149] ERROR [async_call] 异常，重试4次 id=280 roomid=10 game_id=254 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 08:17:44,889 reveal_service.py[line:149] ERROR [async_call] 异常，重试5次 id=280 roomid=10 game_id=254 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 08:17:50,810 reveal_service.py[line:149] ERROR [async_call] 异常，重试6次 id=280 roomid=10 game_id=254 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 08:17:57,741 reveal_service.py[line:149] ERROR [async_call] 异常，重试7次 id=280 roomid=10 game_id=254 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 08:18:05,674 reveal_service.py[line:149] ERROR [async_call] 异常，重试8次 id=280 roomid=10 game_id=254 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 08:18:14,601 reveal_service.py[line:149] ERROR [async_call] 异常，重试9次 id=280 roomid=10 game_id=254 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 08:18:24,528 reveal_service.py[line:149] ERROR [async_call] 异常，重试10次 id=280 roomid=10 game_id=254 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 08:22:43,466 reveal_service.py[line:149] ERROR [async_call] 异常，重试1次 id=287 roomid=10 game_id=261 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 08:22:45,382 reveal_service.py[line:149] ERROR [async_call] 异常，重试2次 id=287 roomid=10 game_id=261 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 08:22:48,490 reveal_service.py[line:149] ERROR [async_call] 异常，重试3次 id=287 roomid=10 game_id=261 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 08:22:53,717 reveal_service.py[line:149] ERROR [async_call] 异常，重试4次 id=287 roomid=10 game_id=261 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 08:22:59,950 reveal_service.py[line:149] ERROR [async_call] 异常，重试5次 id=287 roomid=10 game_id=261 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 08:23:05,889 reveal_service.py[line:149] ERROR [async_call] 异常，重试6次 id=287 roomid=10 game_id=261 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 08:23:12,808 reveal_service.py[line:149] ERROR [async_call] 异常，重试7次 id=287 roomid=10 game_id=261 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 08:23:20,724 reveal_service.py[line:149] ERROR [async_call] 异常，重试8次 id=287 roomid=10 game_id=261 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 08:23:29,645 reveal_service.py[line:149] ERROR [async_call] 异常，重试9次 id=287 roomid=10 game_id=261 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 08:23:39,569 reveal_service.py[line:149] ERROR [async_call] 异常，重试10次 id=287 roomid=10 game_id=261 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 08:43:35,757 reveal_service.py[line:149] ERROR [async_call] 异常，重试1次 id=316 roomid=10 game_id=290 =b'error 2018-12-27T08:43:35.755 thread-0  main.cpp:3151                 main                 ] Failed with error: could not insert object, most likely a uniqueness constraint was violated (13)\ncould not insert object, most likely a uniqueness constraint was violated: pending console output: \n\n'
2018-12-27 08:43:37,676 reveal_service.py[line:149] ERROR [async_call] 异常，重试2次 id=316 roomid=10 game_id=290 =b'error 2018-12-27T08:43:37.674 thread-0  main.cpp:3151                 main                 ] Failed with error: could not insert object, most likely a uniqueness constraint was violated (13)\ncould not insert object, most likely a uniqueness constraint was violated: pending console output: \n\n'
2018-12-27 08:43:40,601 reveal_service.py[line:149] ERROR [async_call] 异常，重试3次 id=316 roomid=10 game_id=290 =b'error 2018-12-27T08:43:40.600 thread-0  main.cpp:3151                 main                 ] Failed with error: could not insert object, most likely a uniqueness constraint was violated (13)\ncould not insert object, most likely a uniqueness constraint was violated: pending console output: \n\n'
2018-12-27 08:43:45,830 reveal_service.py[line:149] ERROR [async_call] 异常，重试4次 id=316 roomid=10 game_id=290 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 08:43:50,746 reveal_service.py[line:149] ERROR [async_call] 异常，重试5次 id=316 roomid=10 game_id=290 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 08:43:56,663 reveal_service.py[line:149] ERROR [async_call] 异常，重试6次 id=316 roomid=10 game_id=290 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 08:44:03,586 reveal_service.py[line:149] ERROR [async_call] 异常，重试7次 id=316 roomid=10 game_id=290 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 08:44:11,508 reveal_service.py[line:149] ERROR [async_call] 异常，重试8次 id=316 roomid=10 game_id=290 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 08:44:21,727 reveal_service.py[line:149] ERROR [async_call] 异常，重试9次 id=316 roomid=10 game_id=290 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 08:44:31,656 reveal_service.py[line:149] ERROR [async_call] 异常，重试10次 id=316 roomid=10 game_id=290 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
