2018-12-27 05:19:01,484 reveal_service.py[line:145] ERROR [async_call] 异常，重试1次 id=46 roomid=10 game_id=20 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:19:03,487 reveal_service.py[line:145] ERROR [async_call] 异常，重试2次 id=46 roomid=10 game_id=20 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:19:06,408 reveal_service.py[line:145] ERROR [async_call] 异常，重试3次 id=46 roomid=10 game_id=20 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:19:11,632 reveal_service.py[line:145] ERROR [async_call] 异常，重试4次 id=46 roomid=10 game_id=20 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:19:17,857 reveal_service.py[line:145] ERROR [async_call] 异常，重试5次 id=46 roomid=10 game_id=20 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:19:23,776 reveal_service.py[line:145] ERROR [async_call] 异常，重试6次 id=46 roomid=10 game_id=20 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:19:32,024 reveal_service.py[line:145] ERROR [async_call] 异常，重试7次 id=46 roomid=10 game_id=20 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:19:39,944 reveal_service.py[line:145] ERROR [async_call] 异常，重试8次 id=46 roomid=10 game_id=20 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:19:48,867 reveal_service.py[line:145] ERROR [async_call] 异常，重试9次 id=46 roomid=10 game_id=20 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 05:20:00,100 reveal_service.py[line:145] ERROR [async_call] 异常，重试10次 id=46 roomid=10 game_id=20 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 05:34:43,783 reveal_service.py[line:145] ERROR [async_call] 异常，重试1次 id=68 roomid=10 game_id=42 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:34:45,699 reveal_service.py[line:145] ERROR [async_call] 异常，重试2次 id=68 roomid=10 game_id=42 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:34:48,668 reveal_service.py[line:145] ERROR [async_call] 异常，重试3次 id=68 roomid=10 game_id=42 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:34:52,588 reveal_service.py[line:145] ERROR [async_call] 异常，重试4次 id=68 roomid=10 game_id=42 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:34:57,508 reveal_service.py[line:145] ERROR [async_call] 异常，重试5次 id=68 roomid=10 game_id=42 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:35:03,478 reveal_service.py[line:145] ERROR [async_call] 异常，重试6次 id=68 roomid=10 game_id=42 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:35:11,719 reveal_service.py[line:145] ERROR [async_call] 异常，重试7次 id=68 roomid=10 game_id=42 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:35:19,641 reveal_service.py[line:145] ERROR [async_call] 异常，重试8次 id=68 roomid=10 game_id=42 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 05:35:28,561 reveal_service.py[line:145] ERROR [async_call] 异常，重试9次 id=68 roomid=10 game_id=42 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 05:35:38,489 reveal_service.py[line:145] ERROR [async_call] 异常，重试10次 id=68 roomid=10 game_id=42 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 05:42:06,858 reveal_service.py[line:145] ERROR [async_call] 异常，重试1次 id=78 roomid=10 game_id=52 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:42:08,788 reveal_service.py[line:145] ERROR [async_call] 异常，重试2次 id=78 roomid=10 game_id=52 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:42:13,009 reveal_service.py[line:145] ERROR [async_call] 异常，重试3次 id=78 roomid=10 game_id=52 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:42:16,924 reveal_service.py[line:145] ERROR [async_call] 异常，重试4次 id=78 roomid=10 game_id=52 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:42:21,844 reveal_service.py[line:145] ERROR [async_call] 异常，重试5次 id=78 roomid=10 game_id=52 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:42:27,769 reveal_service.py[line:145] ERROR [async_call] 异常，重试6次 id=78 roomid=10 game_id=52 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:42:34,687 reveal_service.py[line:145] ERROR [async_call] 异常，重试7次 id=78 roomid=10 game_id=52 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:42:42,608 reveal_service.py[line:145] ERROR [async_call] 异常，重试8次 id=78 roomid=10 game_id=52 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:42:51,539 reveal_service.py[line:145] ERROR [async_call] 异常，重试9次 id=78 roomid=10 game_id=52 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 05:43:01,465 reveal_service.py[line:145] ERROR [async_call] 异常，重试10次 id=78 roomid=10 game_id=52 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 05:47:18,715 reveal_service.py[line:145] ERROR [async_call] 异常，重试1次 id=85 roomid=10 game_id=59 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:47:20,733 reveal_service.py[line:145] ERROR [async_call] 异常，重试2次 id=85 roomid=10 game_id=59 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:47:24,956 reveal_service.py[line:145] ERROR [async_call] 异常，重试3次 id=85 roomid=10 game_id=59 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:47:28,930 reveal_service.py[line:145] ERROR [async_call] 异常，重试4次 id=85 roomid=10 game_id=59 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:47:36,462 reveal_service.py[line:145] ERROR [async_call] 异常，重试5次 id=85 roomid=10 game_id=59 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:47:42,383 reveal_service.py[line:145] ERROR [async_call] 异常，重试6次 id=85 roomid=10 game_id=59 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:47:50,617 reveal_service.py[line:145] ERROR [async_call] 异常，重试7次 id=85 roomid=10 game_id=59 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:47:58,535 reveal_service.py[line:145] ERROR [async_call] 异常，重试8次 id=85 roomid=10 game_id=59 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 05:48:08,763 reveal_service.py[line:145] ERROR [async_call] 异常，重试9次 id=85 roomid=10 game_id=59 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 05:48:18,705 reveal_service.py[line:145] ERROR [async_call] 异常，重试10次 id=85 roomid=10 game_id=59 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 05:50:31,180 reveal_service.py[line:145] ERROR [async_call] 异常，重试1次 id=89 roomid=10 game_id=63 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:50:35,709 reveal_service.py[line:145] ERROR [async_call] 异常，重试2次 id=89 roomid=10 game_id=63 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:50:38,629 reveal_service.py[line:145] ERROR [async_call] 异常，重试3次 id=89 roomid=10 game_id=63 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:50:42,547 reveal_service.py[line:145] ERROR [async_call] 异常，重试4次 id=89 roomid=10 game_id=63 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:50:47,466 reveal_service.py[line:145] ERROR [async_call] 异常，重试5次 id=89 roomid=10 game_id=63 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:50:53,390 reveal_service.py[line:145] ERROR [async_call] 异常，重试6次 id=89 roomid=10 game_id=63 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:51:00,315 reveal_service.py[line:145] ERROR [async_call] 异常，重试7次 id=89 roomid=10 game_id=63 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:51:09,547 reveal_service.py[line:145] ERROR [async_call] 异常，重试8次 id=89 roomid=10 game_id=63 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 05:51:18,473 reveal_service.py[line:145] ERROR [async_call] 异常，重试9次 id=89 roomid=10 game_id=63 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 05:51:29,709 reveal_service.py[line:145] ERROR [async_call] 异常，重试10次 id=89 roomid=10 game_id=63 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 06:12:31,278 reveal_service.py[line:145] ERROR [async_call] 异常，重试1次 id=117 roomid=10 game_id=91 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:12:33,197 reveal_service.py[line:145] ERROR [async_call] 异常，重试2次 id=117 roomid=10 game_id=91 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:12:37,474 reveal_service.py[line:145] ERROR [async_call] 异常，重试3次 id=117 roomid=10 game_id=91 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:12:41,390 reveal_service.py[line:145] ERROR [async_call] 异常，重试4次 id=117 roomid=10 game_id=91 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:12:46,311 reveal_service.py[line:145] ERROR [async_call] 异常，重试5次 id=117 roomid=10 game_id=91 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:12:52,235 reveal_service.py[line:145] ERROR [async_call] 异常，重试6次 id=117 roomid=10 game_id=91 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:13:00,480 reveal_service.py[line:145] ERROR [async_call] 异常，重试7次 id=117 roomid=10 game_id=91 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:13:09,724 reveal_service.py[line:145] ERROR [async_call] 异常，重试8次 id=117 roomid=10 game_id=91 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 06:13:18,668 reveal_service.py[line:145] ERROR [async_call] 异常，重试9次 id=117 roomid=10 game_id=91 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 06:13:28,629 reveal_service.py[line:145] ERROR [async_call] 异常，重试10次 id=117 roomid=10 game_id=91 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 06:48:09,858 reveal_service.py[line:145] ERROR [async_call] 异常，重试1次 id=159 roomid=10 game_id=133 =b'error 2018-12-27T06:48:09.857 thread-0  main.cpp:3151                 main                 ] Failed with error: could not insert object, most likely a uniqueness constraint was violated (13)\ncould not insert object, most likely a uniqueness constraint was violated: pending console output: \n\n'
2018-12-27 06:48:11,780 reveal_service.py[line:145] ERROR [async_call] 异常，重试2次 id=159 roomid=10 game_id=133 =b'error 2018-12-27T06:48:11.779 thread-0  main.cpp:3151                 main                 ] Failed with error: could not insert object, most likely a uniqueness constraint was violated (13)\ncould not insert object, most likely a uniqueness constraint was violated: pending console output: \n\n'
2018-12-27 06:48:16,001 reveal_service.py[line:145] ERROR [async_call] 异常，重试3次 id=159 roomid=10 game_id=133 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:48:19,920 reveal_service.py[line:145] ERROR [async_call] 异常，重试4次 id=159 roomid=10 game_id=133 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:48:24,846 reveal_service.py[line:145] ERROR [async_call] 异常，重试5次 id=159 roomid=10 game_id=133 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:48:30,770 reveal_service.py[line:145] ERROR [async_call] 异常，重试6次 id=159 roomid=10 game_id=133 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:48:37,694 reveal_service.py[line:145] ERROR [async_call] 异常，重试7次 id=159 roomid=10 game_id=133 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:48:46,923 reveal_service.py[line:145] ERROR [async_call] 异常，重试8次 id=159 roomid=10 game_id=133 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:48:55,849 reveal_service.py[line:145] ERROR [async_call] 异常，重试9次 id=159 roomid=10 game_id=133 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 06:49:05,847 reveal_service.py[line:145] ERROR [async_call] 异常，重试10次 id=159 roomid=10 game_id=133 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 06:51:25,079 reveal_service.py[line:145] ERROR [async_call] 异常，重试1次 id=163 roomid=10 game_id=137 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:51:28,326 reveal_service.py[line:145] ERROR [async_call] 异常，重试2次 id=163 roomid=10 game_id=137 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:51:33,856 reveal_service.py[line:145] ERROR [async_call] 异常，重试3次 id=163 roomid=10 game_id=137 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:51:39,132 reveal_service.py[line:145] ERROR [async_call] 异常，重试4次 id=163 roomid=10 game_id=137 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:51:44,054 reveal_service.py[line:145] ERROR [async_call] 异常，重试5次 id=163 roomid=10 game_id=137 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:51:49,981 reveal_service.py[line:145] ERROR [async_call] 异常，重试6次 id=163 roomid=10 game_id=137 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:51:56,909 reveal_service.py[line:145] ERROR [async_call] 异常，重试7次 id=163 roomid=10 game_id=137 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:52:04,834 reveal_service.py[line:145] ERROR [async_call] 异常，重试8次 id=163 roomid=10 game_id=137 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:52:13,765 reveal_service.py[line:145] ERROR [async_call] 异常，重试9次 id=163 roomid=10 game_id=137 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 06:52:23,698 reveal_service.py[line:145] ERROR [async_call] 异常，重试10次 id=163 roomid=10 game_id=137 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 06:56:37,266 reveal_service.py[line:145] ERROR [async_call] 异常，重试1次 id=170 roomid=10 game_id=144 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:56:40,504 reveal_service.py[line:145] ERROR [async_call] 异常，重试2次 id=170 roomid=10 game_id=144 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:56:43,427 reveal_service.py[line:145] ERROR [async_call] 异常，重试3次 id=170 roomid=10 game_id=144 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:56:47,341 reveal_service.py[line:145] ERROR [async_call] 异常，重试4次 id=170 roomid=10 game_id=144 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:56:53,565 reveal_service.py[line:145] ERROR [async_call] 异常，重试5次 id=170 roomid=10 game_id=144 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:56:59,489 reveal_service.py[line:145] ERROR [async_call] 异常，重试6次 id=170 roomid=10 game_id=144 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:57:06,430 reveal_service.py[line:145] ERROR [async_call] 异常，重试7次 id=170 roomid=10 game_id=144 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 06:57:15,658 reveal_service.py[line:145] ERROR [async_call] 异常，重试8次 id=170 roomid=10 game_id=144 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 06:57:25,894 reveal_service.py[line:145] ERROR [async_call] 异常，重试9次 id=170 roomid=10 game_id=144 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 06:57:35,824 reveal_service.py[line:145] ERROR [async_call] 异常，重试10次 id=170 roomid=10 game_id=144 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 07:02:48,992 reveal_service.py[line:145] ERROR [async_call] 异常，重试1次 id=178 roomid=10 game_id=152 =b'error 2018-12-27T07:02:48.990 thread-0  main.cpp:3151                 main                 ] Failed with error: could not insert object, most likely a uniqueness constraint was violated (13)\ncould not insert object, most likely a uniqueness constraint was violated: pending console output: \n\n'
2018-12-27 07:02:50,911 reveal_service.py[line:145] ERROR [async_call] 异常，重试2次 id=178 roomid=10 game_id=152 =b'error 2018-12-27T07:02:50.909 thread-0  main.cpp:3151                 main                 ] Failed with error: could not insert object, most likely a uniqueness constraint was violated (13)\ncould not insert object, most likely a uniqueness constraint was violated: pending console output: \n\n'
2018-12-27 07:02:53,844 reveal_service.py[line:145] ERROR [async_call] 异常，重试3次 id=178 roomid=10 game_id=152 =b'error 2018-12-27T07:02:53.843 thread-0  main.cpp:3151                 main                 ] Failed with error: could not insert object, most likely a uniqueness constraint was violated (13)\ncould not insert object, most likely a uniqueness constraint was violated: pending console output: \n\n'
2018-12-27 07:02:57,763 reveal_service.py[line:145] ERROR [async_call] 异常，重试4次 id=178 roomid=10 game_id=152 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:03:02,687 reveal_service.py[line:145] ERROR [async_call] 异常，重试5次 id=178 roomid=10 game_id=152 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:03:08,604 reveal_service.py[line:145] ERROR [async_call] 异常，重试6次 id=178 roomid=10 game_id=152 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:03:15,527 reveal_service.py[line:145] ERROR [async_call] 异常，重试7次 id=178 roomid=10 game_id=152 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:03:24,758 reveal_service.py[line:145] ERROR [async_call] 异常，重试8次 id=178 roomid=10 game_id=152 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:03:35,008 reveal_service.py[line:145] ERROR [async_call] 异常，重试9次 id=178 roomid=10 game_id=152 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 07:03:46,280 reveal_service.py[line:145] ERROR [async_call] 异常，重试10次 id=178 roomid=10 game_id=152 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 07:12:28,118 reveal_service.py[line:145] ERROR [async_call] 异常，重试1次 id=191 roomid=10 game_id=165 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:12:30,032 reveal_service.py[line:145] ERROR [async_call] 异常，重试2次 id=191 roomid=10 game_id=165 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:12:32,948 reveal_service.py[line:145] ERROR [async_call] 异常，重试3次 id=191 roomid=10 game_id=165 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:12:38,175 reveal_service.py[line:145] ERROR [async_call] 异常，重试4次 id=191 roomid=10 game_id=165 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:12:43,102 reveal_service.py[line:145] ERROR [async_call] 异常，重试5次 id=191 roomid=10 game_id=165 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:12:49,022 reveal_service.py[line:145] ERROR [async_call] 异常，重试6次 id=191 roomid=10 game_id=165 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:12:55,997 reveal_service.py[line:145] ERROR [async_call] 异常，重试7次 id=191 roomid=10 game_id=165 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:13:03,920 reveal_service.py[line:145] ERROR [async_call] 异常，重试8次 id=191 roomid=10 game_id=165 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:13:14,139 reveal_service.py[line:145] ERROR [async_call] 异常，重试9次 id=191 roomid=10 game_id=165 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 07:13:24,063 reveal_service.py[line:145] ERROR [async_call] 异常，重试10次 id=191 roomid=10 game_id=165 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 07:19:42,698 reveal_service.py[line:145] ERROR [async_call] 异常，重试1次 id=201 roomid=10 game_id=175 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:19:44,615 reveal_service.py[line:145] ERROR [async_call] 异常，重试2次 id=201 roomid=10 game_id=175 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:19:50,139 reveal_service.py[line:145] ERROR [async_call] 异常，重试3次 id=201 roomid=10 game_id=175 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:19:55,367 reveal_service.py[line:145] ERROR [async_call] 异常，重试4次 id=201 roomid=10 game_id=175 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:20:00,287 reveal_service.py[line:145] ERROR [async_call] 异常，重试5次 id=201 roomid=10 game_id=175 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:20:06,221 reveal_service.py[line:145] ERROR [async_call] 异常，重试6次 id=201 roomid=10 game_id=175 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:20:13,146 reveal_service.py[line:145] ERROR [async_call] 异常，重试7次 id=201 roomid=10 game_id=175 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:20:21,075 reveal_service.py[line:145] ERROR [async_call] 异常，重试8次 id=201 roomid=10 game_id=175 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 07:20:29,997 reveal_service.py[line:145] ERROR [async_call] 异常，重试9次 id=201 roomid=10 game_id=175 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 07:20:39,922 reveal_service.py[line:145] ERROR [async_call] 异常，重试10次 id=201 roomid=10 game_id=175 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 07:31:19,687 reveal_service.py[line:145] ERROR [async_call] 异常，重试1次 id=217 roomid=10 game_id=191 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:31:22,910 reveal_service.py[line:145] ERROR [async_call] 异常，重试2次 id=217 roomid=10 game_id=191 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:31:25,826 reveal_service.py[line:145] ERROR [async_call] 异常，重试3次 id=217 roomid=10 game_id=191 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:31:31,049 reveal_service.py[line:145] ERROR [async_call] 异常，重试4次 id=217 roomid=10 game_id=191 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:31:38,588 reveal_service.py[line:145] ERROR [async_call] 异常，重试5次 id=217 roomid=10 game_id=191 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:31:45,812 reveal_service.py[line:145] ERROR [async_call] 异常，重试6次 id=217 roomid=10 game_id=191 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:31:52,729 reveal_service.py[line:145] ERROR [async_call] 异常，重试7次 id=217 roomid=10 game_id=191 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:32:00,660 reveal_service.py[line:145] ERROR [async_call] 异常，重试8次 id=217 roomid=10 game_id=191 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 07:32:10,897 reveal_service.py[line:145] ERROR [async_call] 异常，重试9次 id=217 roomid=10 game_id=191 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 07:32:20,824 reveal_service.py[line:145] ERROR [async_call] 异常，重试10次 id=217 roomid=10 game_id=191 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 07:38:36,366 reveal_service.py[line:145] ERROR [async_call] 异常，重试1次 id=227 roomid=10 game_id=201 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:38:39,584 reveal_service.py[line:145] ERROR [async_call] 异常，重试2次 id=227 roomid=10 game_id=201 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:38:42,503 reveal_service.py[line:145] ERROR [async_call] 异常，重试3次 id=227 roomid=10 game_id=201 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:38:47,723 reveal_service.py[line:145] ERROR [async_call] 异常，重试4次 id=227 roomid=10 game_id=201 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:38:54,130 reveal_service.py[line:145] ERROR [async_call] 异常，重试5次 id=227 roomid=10 game_id=201 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:39:00,049 reveal_service.py[line:145] ERROR [async_call] 异常，重试6次 id=227 roomid=10 game_id=201 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:39:09,642 reveal_service.py[line:145] ERROR [async_call] 异常，重试7次 id=227 roomid=10 game_id=201 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:39:17,567 reveal_service.py[line:145] ERROR [async_call] 异常，重试8次 id=227 roomid=10 game_id=201 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 07:39:29,153 reveal_service.py[line:145] ERROR [async_call] 异常，重试9次 id=227 roomid=10 game_id=201 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 07:39:40,382 reveal_service.py[line:145] ERROR [async_call] 异常，重试10次 id=227 roomid=10 game_id=201 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 07:40:40,138 reveal_service.py[line:145] ERROR [async_call] 异常，重试1次 id=229 roomid=10 game_id=203 =b'error 2018-12-27T07:40:40.136 thread-0  main.cpp:3151                 main                 ] Failed with error: could not insert object, most likely a uniqueness constraint was violated (13)\ncould not insert object, most likely a uniqueness constraint was violated: pending console output: \n\n'
2018-12-27 07:40:42,059 reveal_service.py[line:145] ERROR [async_call] 异常，重试2次 id=229 roomid=10 game_id=203 =b'error 2018-12-27T07:40:42.058 thread-0  main.cpp:3151                 main                 ] Failed with error: could not insert object, most likely a uniqueness constraint was violated (13)\ncould not insert object, most likely a uniqueness constraint was violated: pending console output: \n\n'
2018-12-27 07:40:46,340 reveal_service.py[line:145] ERROR [async_call] 异常，重试3次 id=229 roomid=10 game_id=203 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:40:51,576 reveal_service.py[line:145] ERROR [async_call] 异常，重试4次 id=229 roomid=10 game_id=203 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:40:57,806 reveal_service.py[line:145] ERROR [async_call] 异常，重试5次 id=229 roomid=10 game_id=203 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:41:05,056 reveal_service.py[line:145] ERROR [async_call] 异常，重试6次 id=229 roomid=10 game_id=203 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:41:11,978 reveal_service.py[line:145] ERROR [async_call] 异常，重试7次 id=229 roomid=10 game_id=203 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100013 invalid room status\npending console output: \x1b[0m\n'
2018-12-27 07:41:21,240 reveal_service.py[line:145] ERROR [async_call] 异常，重试8次 id=229 roomid=10 game_id=203 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 07:41:30,158 reveal_service.py[line:145] ERROR [async_call] 异常，重试9次 id=229 roomid=10 game_id=203 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
2018-12-27 07:41:40,086 reveal_service.py[line:145] ERROR [async_call] 异常，重试10次 id=229 roomid=10 game_id=203 =b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: 100033 game id do not match\npending console output: \x1b[0m\n'
