2018-12-06 16:27:58,870 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 16:28:30,551 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 16:28:44,777 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 16:28:45,855 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: fund pool overdraw\npending console output: \x1b[0m\n'
2018-12-06 16:28:45,855 dice_service.py[line:145] ERROR 〓ASYNC_CALL〓 异常 尝试重试第1次 id=1009 gameid=244 hash=d9f1cc88daa59860f76899dfc83a693403caf5c68b6e658e3c0e8a5853ead5ea seed=72cec27869bf4f9c01bf2085d6ac524094d7b25856043f9bb1194bcb8c435bef  b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: fund pool overdraw\npending console output: \x1b[0m\n'
2018-12-06 16:28:47,165 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: fund pool overdraw\npending console output: \x1b[0m\n'
2018-12-06 16:28:47,165 dice_service.py[line:145] ERROR 〓ASYNC_CALL〓 异常 尝试重试第2次 id=1009 gameid=244 hash=d9f1cc88daa59860f76899dfc83a693403caf5c68b6e658e3c0e8a5853ead5ea seed=72cec27869bf4f9c01bf2085d6ac524094d7b25856043f9bb1194bcb8c435bef  b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: fund pool overdraw\npending console output: \x1b[0m\n'
2018-12-06 16:28:48,499 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: fund pool overdraw\npending console output: \x1b[0m\n'
2018-12-06 16:28:48,499 dice_service.py[line:145] ERROR 〓ASYNC_CALL〓 异常 尝试重试第3次 id=1009 gameid=244 hash=d9f1cc88daa59860f76899dfc83a693403caf5c68b6e658e3c0e8a5853ead5ea seed=72cec27869bf4f9c01bf2085d6ac524094d7b25856043f9bb1194bcb8c435bef  b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: fund pool overdraw\npending console output: \x1b[0m\n'
2018-12-06 16:35:55,628 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 17:41:34,435 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 17:46:28,204 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 17:47:08,522 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 17:47:17,551 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 17:47:33,013 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 17:47:44,514 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 17:48:10,105 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 17:48:25,925 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 17:52:22,551 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 17:53:02,569 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 17:54:27,266 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 17:54:50,017 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 17:55:30,143 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 17:56:02,106 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 17:57:01,656 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 17:57:25,061 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:01:32,725 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:01:57,590 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:05:51,492 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:06:30,980 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:06:47,036 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:08:12,375 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:08:58,191 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:09:31,783 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:09:54,075 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:11:40,357 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:11:43,186 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:12:26,334 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:13:38,911 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:17:08,197 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:17:11,482 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:17:29,003 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:17:56,746 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:19:02,566 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:19:19,161 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:19:35,609 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:21:08,977 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:22:20,078 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:22:49,051 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:25:09,055 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:25:22,233 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:25:59,859 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:26:09,524 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:26:32,605 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:26:50,690 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:26:52,940 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:33:52,072 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:34:06,386 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:34:15,019 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:34:25,602 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-06 18:51:01,364 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-07 00:43:50,089 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-07 01:05:22,252 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-07 01:05:33,991 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-07 01:48:26,549 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-07 02:10:43,167 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-07 02:48:42,801 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-07 02:50:01,596 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-07 02:50:29,754 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-07 02:51:05,892 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-07 02:51:47,080 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-07 02:51:55,630 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-07 02:53:49,572 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-07 02:54:18,667 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-07 02:54:34,664 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-07 02:56:32,183 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-07 02:57:30,455 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
2018-12-07 03:14:43,570 connector.py[line:43] ERROR 〓ASYNC_CALL〓 异常 b'\x1b[31mError 3050003: eosio_assert_message assertion failure\x1b[0m\n\x1b[33mError Details:\nassertion failure with message: game not found\npending console output: \x1b[0m\n'
